"use client";

import { FileText, Info, List, RefreshCw, Sparkles } from "lucide-react";
import * as React from "react";

import { usePlayer } from "@/components/player/player-provider";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { useRegenerateSummary } from "@/hooks/use-api";
import { formatTimestamp } from "@/lib/format";
import type { Chapter, Summary } from "@/lib/types";
import { cn } from "@/lib/utils";

function Card({
  title,
  icon: Icon,
  action,
  children,
}: {
  title: string;
  icon: typeof FileText;
  action?: React.ReactNode;
  children: React.ReactNode;
}) {
  return (
    <section className="rounded-lg bg-white ring-1 ring-grey-200">
      <div className="flex items-center justify-between border-b border-grey-100 px-4 py-3">
        <h2 className="flex items-center gap-2 text-[13px] font-semibold text-grey-900">
          <Icon className="h-4 w-4 text-grey-400" />
          {title}
        </h2>
        {action}
      </div>
      <div className="px-4 py-3.5">{children}</div>
    </section>
  );
}

export function SummaryPanel({
  meetingId,
  summary,
  chapters,
  hasTranscript,
}: {
  meetingId: number;
  summary: Summary | null;
  chapters: Chapter[];
  hasTranscript: boolean;
}) {
  const { currentMs, seek } = usePlayer();
  const regenerate = useRegenerateSummary(meetingId);

  if (!summary || !hasTranscript) {
    return (
      <Card title="Meeting summary" icon={Sparkles}>
        <p className="text-[13px] text-grey-500">
          There is no transcript on this meeting yet. Upload one and the summary, chapters and
          action items will be generated from it.
        </p>
      </Card>
    );
  }

  const bullets = (summary.bullet_gist ?? "")
    .split("\n")
    .map((line) => line.trim())
    .filter(Boolean);

  // The chapter containing the playhead, so the outline tracks playback.
  const activeChapterId = chapters.find(
    (chapter) => currentMs >= chapter.start_ms && currentMs <= chapter.end_ms,
  )?.id;

  return (
    <div className="space-y-4">
      {summary.gist ? (
        <div className="rounded-lg bg-brand-25 p-4 ring-1 ring-brand-100">
          <p className="flex items-center gap-1.5 text-[11px] font-semibold tracking-wide text-brand-700 uppercase">
            <Sparkles className="h-3 w-3" />
            Gist
          </p>
          <p className="mt-1.5 text-[13px] leading-relaxed text-grey-800">{summary.gist}</p>
        </div>
      ) : null}

      <Card
        title="Overview"
        icon={FileText}
        action={
          <Button
            variant="ghost"
            size="sm"
            onClick={() => regenerate.mutate()}
            disabled={regenerate.isPending}
          >
            <RefreshCw className={cn("h-3.5 w-3.5", regenerate.isPending && "animate-spin")} />
            Regenerate
          </Button>
        }
      >
        {bullets.length ? (
          <ul className="space-y-2">
            {bullets.map((bullet, index) => (
              <li key={index} className="text-[13px] leading-relaxed text-grey-700">
                {bullet}
              </li>
            ))}
          </ul>
        ) : null}

        {summary.overview ? (
          <div className="mt-4 space-y-3 border-t border-grey-100 pt-3.5">
            {summary.overview.split("\n\n").map((paragraph, index) => (
              <p key={index} className="text-[13px] leading-relaxed text-grey-600">
                {paragraph}
              </p>
            ))}
          </div>
        ) : null}

        {/* Provenance, stated plainly. The summary is extractive, and saying so
            is more credible than implying a model wrote it. */}
        <p className="mt-4 flex items-start gap-1.5 border-t border-grey-100 pt-3 text-[11px] leading-relaxed text-grey-400">
          <Info className="mt-px h-3 w-3 shrink-0" />
          {summary.generated_by === "heuristic"
            ? "Generated on the server by TF-IDF extractive summarisation — deterministic, and derived only from this transcript."
            : `Generated by ${summary.model ?? summary.generated_by}.`}
        </p>
      </Card>

      {chapters.length ? (
        <Card title="Outline" icon={List}>
          <ol className="space-y-0.5">
            {chapters.map((chapter) => (
              <li key={chapter.id}>
                <button
                  type="button"
                  onClick={() => seek(chapter.start_ms)}
                  className={cn(
                    "flex w-full items-start gap-3 rounded-sm px-2 py-2 text-left transition-colors",
                    chapter.id === activeChapterId ? "bg-brand-50" : "hover:bg-grey-50",
                  )}
                >
                  <span
                    className={cn(
                      "mt-px w-11 shrink-0 text-[11px] tabular-nums",
                      chapter.id === activeChapterId
                        ? "font-semibold text-brand-700"
                        : "text-grey-400",
                    )}
                  >
                    {formatTimestamp(chapter.start_ms)}
                  </span>
                  <span className="min-w-0 flex-1">
                    <span className="block text-[13px] font-medium text-grey-800">
                      {chapter.title}
                    </span>
                    {chapter.gist ? (
                      <span className="mt-0.5 line-clamp-2 block text-[12px] leading-snug text-grey-500">
                        {chapter.gist}
                      </span>
                    ) : null}
                  </span>
                </button>
              </li>
            ))}
          </ol>
        </Card>
      ) : null}

      {summary.keywords.length ? (
        <Card title="Keywords" icon={Sparkles}>
          <div className="flex flex-wrap gap-1.5">
            {summary.keywords.map((keyword) => (
              <Badge key={keyword}>{keyword}</Badge>
            ))}
          </div>
        </Card>
      ) : null}
    </div>
  );
}
